; ============================================
; codegen.asm - IR → NASM 汇编代码生成器 (跨平台版)
; ============================================
; 功能:
;   从 IR 缓冲区读取条目，生成对应的 NASM 汇编文本
;   输出到全局输出缓冲区 (通过 write_char / write_output)
;
; 导出的函数:
;   generate_all()         → 生成所有 IR 条目的汇编代码
;   generate_entry(rdi=IR条目指针) → 生成单条 IR 条目的汇编
; ============================================

default rel

%include "config.inc"
%include "ir_defs.inc"

; ============================================
; 导出符号
; ============================================
global generate_all
global generate_entry

; ============================================
; 外部引用
; ============================================
extern write_char
extern write_output
extern ir_entry_count
extern get_ir_entry

; ============================================
; 常量字符串
; ============================================
section .data
str_comma_space db ', ', 0
str_section     db "section .text", 10
                db "global _start", 10
                db 10
                db "_start:", 10, 0
str_indent      db "    ", 0        ; 4空格缩进

section .text

; ============================================
; generate_all: 生成所有 IR 条目的汇编代码
; 输出: 使用 write_char/write_output 写入输出缓冲区
; ============================================
generate_all:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    push r12
    push r13

    ; 输出文件头
    load_addr rsi, str_section
    call write_output

    ; 输出注释
    mov al, ';'
    call write_char
    mov al, ' '
    call write_char
    load_addr rsi, str_gen_comment
    call write_output
    mov al, 10
    call write_char

    ; 遍历所有 IR 条目
    load_addr r13, ir_entry_count
    mov r12, [r13]
    test r12, r12
    jz .done

    xor r13, r13           ; 索引 = 0

.loop:
    ; 获取 IR 条目指针
    mov rdi, r13
    call get_ir_entry
    test rax, rax
    jz .next

    ; 生成该条目的汇编代码
    mov rdi, rax
    call generate_entry

.next:
    inc r13
    cmp r13, r12
    jl .loop

.done:
    pop r13
    pop r12
    leave
    ret

; ============================================
; generate_entry: 生成单条 IR 条目的汇编
; 输入: rdi = IR 条目指针
; ============================================
generate_entry:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    push r12
    push r14

    mov r12, rdi           ; r12 = IR 条目指针

    ; 输出缩进
    load_addr rsi, str_indent
    call write_output

    ; 输出助记符
    mov rsi, [r12 + IR_MNEMONIC_OFF]
    test rsi, rsi
    jnz .has_mnemonic
    ; 没有助记符 → 输出原始字节
    jmp .output_raw

.has_mnemonic:
    call write_output

    ; 获取操作数数量
    mov rax, [r12 + IR_OPCOUNT_OFF]
    test rax, rax
    jz .end_line           ; 没有操作数，直接换行

    ; 保存 op_count — mov al, ' ' 会覆盖 rax 低字节
    push rax
    ; 输出空格
    mov al, ' '
    call write_char
    pop rax                ; 恢复 op_count

    ; 输出操作数 (逗号分隔)
    xor r14, r14           ; 操作数索引
.op_loop:
    cmp r14, 4
    jge .end_line
    cmp r14, rax           ; rax = 正确的 op_count
    jge .end_line

    ; 输出逗号 (非第一个操作数)
    test r14, r14
    jz .no_comma
    load_addr rsi, str_comma_space
    call write_output

.no_comma:
    ; 获取操作数指针
    mov rsi, [r12 + IR_OP1_OFF + r14 * 8]
    test rsi, rsi
    jz .next_op

    call write_output

.next_op:
    inc r14
    jmp .op_loop

.end_line:
    ; 换行
    mov al, 10
    call write_char

    jmp .exit

.output_raw:
    ; 输出 "db 0xNN"
    load_addr rsi, str_db
    call write_output
    mov al, ' '
    call write_char
    mov al, '0'
    call write_char
    mov al, 'x'
    call write_char

    ; 提取原始字节
    xor rax, rax
    mov al, [r12 + IR_RAW_OFF]
    push rax
    shr al, 4
    call nybble_to_hex
    call write_char
    pop rax
    and al, 0x0F
    call nybble_to_hex
    call write_char

    mov al, 10
    call write_char

.exit:
    pop r14
    pop r12
    leave
    ret

; ============================================
; nybble_to_hex: 半字节转十六进制字符
; 输入: al = 0-15
; 输出: al = 字符
; ============================================
nybble_to_hex:
    push rbp
    mov rbp, rsp
    cmp al, 9
    jbe .digit
    add al, 'A' - 10
    jmp .exit
.digit:
    add al, '0'
.exit:
    leave
    ret

; ============================================
; 静态数据
; ============================================
section .data
str_db:          db "db", 0
str_gen_comment: db "Generated by NTF-Demo v2.0", 0
